<a href="https://colab.research.google.com/github/Mayank1498/Ashutosh-PMishra/blob/main/Mayank_Sharma_081_IIOT_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x)
print(x.shape)
print(x.dtype)

[1 2 3 4 5 6 7]
(7,)
int64


In [2]:
x=np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
x.shape
x[3,2]
x[3,:]
x[:,1]
x[1:3,1:3]

array([[4, 5],
       [6, 7]])

In [3]:
x=np.arange(1,10,.5)
x=np.arange(10,1,-3.3)
x
x=np.linspace(0,10,5)
x

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [4]:
x=np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
x.shape
x=np.expand_dims(x,axis=1)
print(x.shape)
x1=np.squeeze(x,axis=1)
print(x1.shape)
x2=x1.flatten()
print(x2)

(4, 1, 3)
(4, 3)
[1 2 3 3 4 5 5 6 7 7 8 9]


In [5]:
x=np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
print(x.shape)
x1=np.reshape(x,(6,2))
print(x1.shape)
x1=np.resize(x,(9,20))
print(x1.shape)
print(x1)

(4, 3)
(6, 2)
(9, 20)
[[1 2 3 3 4 5 5 6 7 7 8 9 1 2 3 3 4 5 5 6]
 [7 7 8 9 1 2 3 3 4 5 5 6 7 7 8 9 1 2 3 3]
 [4 5 5 6 7 7 8 9 1 2 3 3 4 5 5 6 7 7 8 9]
 [1 2 3 3 4 5 5 6 7 7 8 9 1 2 3 3 4 5 5 6]
 [7 7 8 9 1 2 3 3 4 5 5 6 7 7 8 9 1 2 3 3]
 [4 5 5 6 7 7 8 9 1 2 3 3 4 5 5 6 7 7 8 9]
 [1 2 3 3 4 5 5 6 7 7 8 9 1 2 3 3 4 5 5 6]
 [7 7 8 9 1 2 3 3 4 5 5 6 7 7 8 9 1 2 3 3]
 [4 5 5 6 7 7 8 9 1 2 3 3 4 5 5 6 7 7 8 9]]


In [7]:
########### RANDOM NUMBER
a=np.random.random()
print(a)
b=np.random.random((3,4))
print(b)
c=np.random.randint(0,100)
print(c)
d=np.random.randint(0,100,(3,4))
print(d)

0.13047956293063157
[[0.16519562 0.31396456 0.16063702 0.63903173]
 [0.70217843 0.93140083 0.25224443 0.49295317]
 [0.55896894 0.22253166 0.73263288 0.11786521]]
6
[[52  2 15 84]
 [ 2 38 88 73]
 [35  4 82 56]]


In [8]:
np.random.choice([1,2,3,4,5,6])
np.random.shuffle([1,2,3,4,5])
#np.random.seed(4)
x=np.random.randint(1,100)
x

68

In [9]:
a=np.random.randint(0,100,(3,10))
print(a)
print(np.argmax(a))
print(np.argmax(a,axis=0)) # column wise
print(np.argmax(a,axis=1)) # row wise

[[97 12 82 81 53  4 15 64 64  0]
 [22 92 40 54 16 54 90 81 24 61]
 [63 21 77 68  6 85 93 68 18 25]]
0
[0 1 0 0 0 2 2 1 0 1]
[0 1 6]


In [10]:
np.exp(1)
np.sqrt(2)
np.std([1,2,3,4,5,6])
np.mean([1,2,3,4,5,6])
np.median([4,5,6,7,8,9])
np.mean([[3,4,5,6],[4,5,6,8]],axis=1)

array([4.5 , 5.75])

In [11]:
a=np.random.randint(0,100,(3,3))
b=np.random.randint(0,10,(3,3))
print(a+b)
print(a-b)
print(a*b) # element wise multiplication
print(np.dot(a,b))
print(a.dot(b))
print(a/b)
print(a%2)
print(a**2)
print(a.T)

[[ 90  42  30]
 [ 84  11 104]
 [ 84  88  20]]
[[72 28 20]
 [66  3 92]
 [68 88  6]]
[[729 245 125]
 [675  28 588]
 [608   0  91]]
[[1244  707  790]
 [1522  553 1103]
 [1580  884  999]]
[[1244  707  790]
 [1522  553 1103]
 [1580  884  999]]
[[ 9.          5.          5.        ]
 [ 8.33333333  1.75       16.33333333]
 [ 9.5                inf  1.85714286]]
[[1 1 1]
 [1 1 0]
 [0 0 1]]
[[6561 1225  625]
 [5625   49 9604]
 [5776 7744  169]]
[[81 75 76]
 [35  7 88]
 [25 98 13]]


<ipython-input-11-18da2cac46cc>:8: RuntimeWarning: divide by zero encountered in divide
  print(a/b)
